#!/bin/bash

env_file="./js/env.js"
env_source=".env"
# cat $env_source
> $env_file
echo "ENV = { " >> $env_file
while read -r line; do
    echo "$line," >> $env_file
done < $env_source

echo " } " >> $env_file